image: Visual Studio 2019
version: build '{build}'
configuration: Release
platform: Any CPU

before_build:
  - cmd: nuget restore src\AwesomeProxy.sln
  
environment:
  my_variable:
    secure: GWztiV993airUIgYQa/8Yp0jZuZ9IWVjAJDxwBRTOvN2C5pBqlArgsUY4uqrGujp


build_script:
  - dotnet build src\AwesomeProxy.sln -c Release
  - dotnet test src\AwesomeProxy.Test
after_build:
  - dotnet pack src\AwesomeProxy

deploy:
- provider: NuGet
  api_key:
    secure: GWztiV993airUIgYQa/8Yp0jZuZ9IWVjAJDxwBRTOvN2C5pBqlArgsUY4uqrGujp
  on:
    branch: master  
  artifact: /.*(\.|\.s)nupkg/
  
build:
  publish_nuget: true
  
nuget:
  project_feed: true
        
artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.snupkg'
