image: Visual Studio 2019
version: build '{build}'
configuration: Release
platform: Any CPU

environment:
  my_variable:
    secure: GWztiV993airUIgYQa/8Yp0jZuZ9IWVjAJDxwBRTOvN2C5pBqlArgsUY4uqrGujp

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: nuget restore src\AwesomeProxy.sln

build_script:
  - cmd: Msbuild restore src\AwesomeProxy.sln

# after_build:
  # - dotnet pack src\AwesomeProxy

# deploy:
# - provider: NuGet
  # api_key:
    # secure: GWztiV993airUIgYQa/8Yp0jZuZ9IWVjAJDxwBRTOvN2C5pBqlArgsUY4uqrGujp
  # on:
    # branch: master  
  # artifact: /.*(\.|\.s)nupkg/
  
build:
  publish_nuget: true
  
nuget:
  project_feed: true
        
artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.snupkg'
